[package]
name = "navigation_robot_custom_interfaces"
version = "0.0.0"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }
action_msgs = "*"
unique_identifier_msgs = "*"
std_msgs = "*"
builtin_interfaces = "*"

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde', 'action_msgs/serde', 'unique_identifier_msgs/serde', 'std_msgs/serde', 'builtin_interfaces/serde']
